server.port=${PORT:8082}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billingdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:billing}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:billing}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.web.resources.static-locations=classpath:/static/,file:./public/
app.tax.percent=10

