server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/billingdb
spring.datasource.username=billing
spring.datasource.password=billing
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.web.resources.static-locations=classpath:/static/,file:./public/
app.tax.percent=10

